# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  samplecatservicegrpc:
    image: samplecatservicegrpc
    build:
      context: .
      dockerfile: samplecatservice.grpc/Dockerfile
    ports:
      - 5161:5161
