# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  samplecatserviceapi:
    image: samplecatserviceapi
    build:
      context: .
      dockerfile: samplecatservice.api/Dockerfile
    depends_on:
      - redis
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 5160:5160
  samplecatservicegrpc:
    image: samplecatservicegrpc
    build:
      context: .
      dockerfile: samplecatservice.grpc/Dockerfile
    depends_on:
      - redis
    ports:
      - 5161:5161
  redis:
      image: 'redis:alpine'
      ports:
      - "6379:6379"
      environment:
        - ALLOW_EMPTY_PASSWORD=yes